### ISSUE TITLE
请问一下抗锯齿怎么没有效果呢

### ISSUE THREAD

**Issue by kolvs** [xiaschina/ArcView#1]
请问一下抗锯齿怎么没有效果呢，paint， canvas都加了抗锯齿

**Comment by xiaschina** [comment]
您好，最近一段比较忙，刚看到，不好意思哈，canvas.clipPath()这个函数绘制出来的图形会带锯齿。
解决锯齿需要新引入一个新的paint,设置抗锯齿，调用canvas.drawPath()即可。代码如下：
       drawArc();
        mPaint.setColor(mBgColor);
        mPath.moveTo(mSPointF.x, mSPointF.y);
        mPath.quadTo(mCPointF.x, mCPointF.y, mEPointF.x, mEPointF.y);
        int saveCount = canvas.saveLayer(0, 0, getWidth(), getHeight(), null, Canvas.ALL_SAVE_FLAG);
        super.onDraw(canvas);
        antiPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.MULTIPLY));
        canvas.drawPath(mPath, antiPaint);
        canvas.restoreToCount(saveCount);
        antiPaint.setXfermode(null);
其中antiPaint只需设置抗拒锯齿即可。
